#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2014-2017 Spotify AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
from wsgiref import simple_server
from crtauth import server
from crtauth import key_provider
from crtauth import wsgi


def application(_, start_response):
    response = "Hello, world\n"
    status = '200 OK'
    response_headers = [('Content-Type', 'text/plain'),
                        ('Content-Length', str(len(response)))]
    start_response(status, response_headers)
    return response,


if __name__ == '__main__':
    # set up logging
    logging.basicConfig()

    # set up AuthServer instance
    auth_server = server.AuthServer("a_secret",
                                    key_provider.FileKeyProvider("."),
                                    "localhost")
    # create middleware instance
    middleware = wsgi.CrtauthMiddleware(application, auth_server)

    simple_server.make_server('', 8080, middleware).serve_forever()
